insert into public.categories (name, slug)
values
  ('Accessibility', 'accessibility'),
  ('Accounting', 'accounting'),
  ('AdTech', 'adtech'),
  ('Affiliate Marketing', 'affiliate-marketing'),
  ('API Management', 'api-management'),
  ('App Development', 'app-development'),
  ('AR & VR', 'ar-vr'),
  ('Audio & Music', 'audio-music'),
  ('Automation', 'automation'),
  ('Blockchain & Web3', 'blockchain-web3'),
  ('Brand Management', 'brand-management'),
  ('Business Intelligence', 'business-intelligence'),
  ('CRM', 'crm'),
  ('Cloud Computing', 'cloud-computing'),
  ('Cloud Infrastructure', 'cloud-infrastructure'),
  ('Community Platforms', 'community-platforms'),
  ('Compliance', 'compliance'),
  ('Construction Tech', 'construction-tech'),
  ('Content Management', 'content-management'),
  ('Creator Tools', 'creator-tools'),
  ('Customer Experience', 'customer-experience'),
  ('Customer Success', 'customer-success'),
  ('Customer Support', 'customer-support'),
  ('Data Engineering', 'data-engineering'),
  ('Data Management', 'data-management'),
  ('Data Science', 'data-science'),
  ('Data Visualization', 'data-visualization'),
  ('Databases', 'databases'),
  ('DevOps', 'devops'),
  ('Digital Asset Management', 'digital-asset-management'),
  ('Digital Signage', 'digital-signage'),
  ('Document Management', 'document-management'),
  ('Email', 'email'),
  ('Energy & Climate', 'energy-climate'),
  ('Enterprise Software', 'enterprise-software'),
  ('Event Management', 'event-management'),
  ('Facilities Management', 'facilities-management'),
  ('Food & Beverage', 'food-beverage'),
  ('Forms & Surveys', 'forms-surveys'),
  ('Gaming', 'gaming'),
  ('Government Tech', 'government-tech'),
  ('HR & Recruiting', 'hr-recruiting'),
  ('Healthcare', 'healthcare'),
  ('Hosting', 'hosting'),
  ('Identity & Access', 'identity-access'),
  ('Insurtech', 'insurtech'),
  ('Internal Tools', 'internal-tools'),
  ('IoT', 'iot'),
  ('Legal Tech', 'legal-tech'),
  ('Logistics & Supply Chain', 'logistics-supply-chain'),
  ('Low-Code', 'low-code'),
  ('Machine Learning', 'machine-learning'),
  ('Manufacturing', 'manufacturing'),
  ('Market Research', 'market-research'),
  ('Messaging', 'messaging'),
  ('Mobile Apps', 'mobile-apps'),
  ('No-Code', 'no-code'),
  ('Nonprofit Tech', 'nonprofit-tech'),
  ('Open Source', 'open-source'),
  ('Operations', 'operations'),
  ('Payments', 'payments'),
  ('Personal Finance', 'personal-finance'),
  ('Product Management', 'product-management'),
  ('Project Management', 'project-management'),
  ('Property Tech', 'property-tech'),
  ('Public Relations', 'public-relations'),
  ('Real Estate', 'real-estate'),
  ('Remote Work', 'remote-work'),
  ('Retail Tech', 'retail-tech'),
  ('Robotics', 'robotics'),
  ('Sales', 'sales'),
  ('Search', 'search'),
  ('SEO', 'seo'),
  ('Social Media Management', 'social-media-management'),
  ('Sports Tech', 'sports-tech'),
  ('Sustainability', 'sustainability'),
  ('Task Management', 'task-management'),
  ('Team Collaboration', 'team-collaboration'),
  ('Telecommunications', 'telecommunications'),
  ('Travel & Hospitality', 'travel-hospitality'),
  ('Video & Streaming', 'video-streaming'),
  ('Virtual Events', 'virtual-events'),
  ('Web Development', 'web-development'),
  ('Workplace Management', 'workplace-management')
on conflict (slug) do update
set name = excluded.name;
